@startuml Activity_Diagram

title Update Object \n

start

floating note left: Activities in <color:DeepSkyBlue>DeepSkyBlue \nare run by the system on the obj

while (Simulation Running?) 

split
#DeepSkyBlue:Obj 1 Get Influencer States;

note left
  "Could be parallelised"
  end note
  
split
  :Request State 1;
    note left
      "The list of influencers"
    end note
 
split again
  :Request State 2;
split again
  :Request State 3;
end split

split again
   :Obj 2...;
   :Request influencers;
end split
   

#DeepSkyBlue:Process Combined Influencers State;

if (State Changed?) then (yes)
  : React to State Change;
  if (Change Impacts Influence?) then (yes)
   :Notify all objects influence input changed;
   
   note left
     "eg position changed"
     end note
     
  else (no)
  endif
else (no)
  
endif

endwhile


stop

@enduml
