@startuml

title Classes - Class Diagram

abstract class Observable

Observable <|.. ConcreteObservable


abstract class Observable{
 -observers: ObserverBase[0..*]

 +Register(Observer o)
 +Deregister(Observer o)
 +Notify()
}

class ConcreteObservable


interface ObserverBase


@enduml
